name: "wMBus MQTT Bridge NewGUI"
description: "[NEWGUI] MQTT RAW HEX -> wmbusmeters (stdin:hex) -> MQTT + Home Assistant Discovery"
version: "1.5.11-dev.21"
slug: "wmbus_mqtt_bridge_newgui"
stage: experimental
image: "ghcr.io/kustonium/{arch}-addon-wmbus_mqtt_bridge-dev"
arch:
  - amd64
  - aarch64

init: false

ingress: true
ingress_port: 8099
hassio_api: true
panel_icon: mdi:gauge
panel_title: "wMBus Bridge NewGUI"
services:
  - mqtt:want

options:
  raw_topic: "wmbus/+/telegram"
  loglevel: "normal"
  filter_hex_only: true
  debug_every_n: 0

  search_mode: false
  search_expected_value_m3: 0
  search_tolerance_m3: 0.05
  search_delta_mode: false
  search_min_delta_m3: 0.001
  search_topic: "wmbus/search/candidates"

  discovery_enabled: true
  discovery_prefix: "homeassistant"
  discovery_retain: true

  state_prefix: "wmbusmeters"
  state_retain: false

  mqtt_mode: "auto"
  external_mqtt_host: ""
  external_mqtt_port: 1883
  external_mqtt_username: ""
  external_mqtt_password: ""

  meters: []

schema:
  raw_topic: str
  loglevel: list(normal|verbose|debug)
  filter_hex_only: bool
  debug_every_n: int
  search_mode: bool
  search_expected_value_m3: float
  search_tolerance_m3: float
  search_delta_mode: bool
  search_min_delta_m3: float
  search_topic: str
  discovery_enabled: bool
  discovery_prefix: str
  discovery_retain: bool
  state_prefix: str
  state_retain: bool
  mqtt_mode: list(auto|ha|external)
  external_mqtt_host: str?
  external_mqtt_port: int
  external_mqtt_username: str?
  external_mqtt_password: str?
  meters:
    - id: str
      meter_id: str
      type: list(auto|abbb23|aerius|amiplus|apator08|apator162|apator172|apatoreitn|aptmbusna|aquastream|aventieshca|aventieswm|c5isf|caltose|cma12w|dme_07|dme173|ebzwmbe|ehzp|ei6500|elf|elf2|elster|eltako|elvsense|em24|emerlin868|enercal|engelmann_faw|esyswm|eurisii|ev200|evo868|fhkvdataiii|fhkvdataiv|fiowater|flowiq2200|gransystems|gwfgas|hcae2|hydrocalm3|hydrocalm4|hydroclimav2|hydrodigit|hydrus|iem3000|ime|iperl|istaheat|itron|itronheat|iwmtx5|izar|kaden|kamheat|kampress|kamwater|lansendw|lansenpu|lansenrp|lansensm|lansenth|lse_07_17|lse_08|maddalena|microclima|minomess|mkradio3|mkradio3a|mkradio4|mkradio4a|multical21|munia|nemo|nzr|omnipower|op041a|picoflux|piigth|pollucomf|q400|qcaloric|qheat|qheat_55_us|qheat5us|qheatus|qheatv2|qsmoke|qualcosonic|qwater|qwaterv2|relhca|rfmamb|sensostar|sharky|sharky774|sontex868|supercal|supercom587|topaseskr|tsd2|ultraheat|ultrimis|unismart|vario411|vario451|vario451mid|waterstarm|watertech|weh_07|werhlemodwm|zennerhca|other)
      type_other: str?
      key: str?
